nationality(dominican,dominican_republic).
nationality(dutch,netherlands).
nationality(manxwoman,manx).
nationality(afghan,afghanistan).
nationality(albanian,albania).
nationality(algerian,algeria).
nationality(american,united_states).
nationality(american_samoan,american_samoa).
nationality(andorran,andorra).
nationality(angolan,angola).
nationality(anguillan,anguilla).
nationality(antiguan,antigua).
nationality(argentine,argentina).
nationality(armenian,armenia).
nationality(aruban,aruba).
nationality(australian,australia).
nationality(austrian,austria).
nationality(azerbaijani,azerbadijan).
nationality(bahamian,bahamas).
nationality(bahraini,bahrain).
nationality(bangladeshi,bangladesh).
nationality(barbadian,barbados).
nationality(barbudan,barbuda).
nationality(basotho,basotho).
nationality(batswana,botswana).
nationality(belarusian,belarus).
nationality(belgian,belgium).
nationality(belizean,belize).
nationality(beninese,benin).
nationality(bermudian,bermuda).
nationality(bhutanese,bhutan).
nationality(bolivian,bolivia).
nationality(bosnian,bosnia).
nationality(brazilian,brazil).
nationality(british,britain).
nationality(british_virgin_islander,british_virgin_islands).
nationality(briton,britain).
nationality(bruneian,brunei).
nationality(bulgarian,bulgaria).
nationality(burkinabe,burkina).
nationality(burmese,burma).
nationality(burundian,burundi).
nationality(cambodian,cambodia).
nationality(cameroonian,cameroon).
nationality(canadian,canada).
nationality(cape_verdean,cape_verde).
nationality(caymanian,cayman_islands).
nationality(central_african,central_africa).
nationality(chadian,chad).
nationality(channel_islander,channel_islands).
nationality(chilean,chili).
nationality(chinese,china).
nationality(christmas_island,christmas_islands).
nationality(christmas_islander,christmas_islands).
nationality(chuukese,chuuk).
nationality(cocos_islander,cocos_islands).
nationality(colombian,colombia).
nationality(comoran,comoros).
nationality(congo,congo).
nationality(congolese,congo).
nationality(cook_islander,cook_islands).
nationality(costa_rican,costa_rica).
nationality(croat,croatia).
nationality(croatian,croatia).
nationality(cuban,cuba).
nationality(cypriot,cyprus).
nationality(czech,czech_republic).
nationality(dane,denmark).
nationality(danish,denmark).
nationality(djiboutian,djibouti).
nationality(dutch_antillean,netherlands_antilles).
nationality(dutchman,netherlands).
nationality(dutchwoman,netherlands).
nationality(ecuadorian,ecuador).
nationality(egyptian,egypt).
nationality(emirati,united_arab_emirates).
nationality(equatoguinean,equatorial_guinea).
nationality(equatorial_guinean,equatorial_guinea).
nationality(eritrean,eritrea).
nationality(estonian,estonia).
nationality(ethiopian,ethiopia).
nationality(falkland_islander,falkland_islands).
nationality(faroese,faroe_islands).
nationality(fijian,fiji).
nationality(filipino,philippines).
nationality(finn,finland).
nationality(finnish,finland).
nationality(french,france).
nationality(french_guianese,french_guiana).
nationality(french_polynesian,french_polynesia).
nationality(frenchman,france).
nationality(frenchwoman,france).
nationality(futunan,futuna).
nationality(gabonese,gabon).
nationality(gambian,gambia).
nationality(georgian,georgia).
nationality(german,germany).
nationality(ghanaian,ghana).
nationality(gibraltar,gibraltar).
nationality(gibraltarian,gibraltar).
nationality(greek,greece).
nationality(greenlander,greenland).
nationality(greenlandic,greenland).
nationality(grenadian,grenada).
nationality(guadeloupe,guadeloupe).
nationality(guadeloupian,guadeloupe).
nationality(guamanian,guam).
nationality(guatemalan,guatemalia).
nationality(guinean,guinea).
nationality(guyanese,guyana).
nationality(haitian,haiti).
nationality(herzegovinian,herzegovinia).
nationality(honduran,honduras).
nationality(hong_konger,hong_kong).
nationality(hungarian,hungary).
nationality(icelander,iceland).
nationality(icelandic,iceland).
nationality(indian,india).
nationality(indonesian,indonesia).
nationality(iranian,iran).
nationality(iraqi,iraq).
nationality(irish,ireland).
nationality(irishman,ireland).
nationality(irishwoman,ireland).
nationality(israeli,israel).
nationality(italian,italy).
nationality(ivoirian,'cote_d\'ivoire').
nationality(jamaican,jamaica).
nationality(japanese,japan).
nationality(jordanian,jordan).
nationality(kazakhstani,kazakhstan).
nationality(kenyan,kenya).
nationality(kittitian,saint_kitts).
nationality(korean,korea).
nationality(north_korean,north_korea).
nationality(south_korean,south_korea).
nationality(kuwaiti,kuwait).
nationality(kyrgyzstani,kyrgyzstan).
nationality(lao,laos).
nationality(laotian,laos).
nationality(latvian,latvia).
nationality(lebanese,lebanon).
nationality(liberian,liberia).
nationality(libyan,libya).
nationality(liechtensteiner,liechtenstein).
nationality(lithuanian,lithuania).
nationality(luxembourger,luxembourg).
nationality(macedonian,macedonia).
nationality(malagasy,malaga).
nationality(malawian,malawi).
nationality(malaysian,malaysia).
nationality(maldivian,maldives).
nationality(malian,mali).
nationality(maltese,malta).
nationality(manx,manx).
nationality(manxman,manx).
nationality(marshallese,marshall_islands).
nationality(martiniquais,martinique).
nationality(mauritanian,mauritiania).
nationality(mauritian,mauritius).
nationality(mexican,mexico).
nationality(micronesian,micronesia).
nationality(moldovan,moldova).
nationality(monacan,monaco).
nationality(monegasque,monaco).
nationality(mongolian,mongolia).
nationality(montenegrin,montenegro).
nationality(montserratian,montserrat).
nationality(moroccan,morroco).
nationality(mosotho,lesotho).
nationality(motswana,botswana).
nationality(mozambican,mozambique).
nationality(namibian,namibia).
nationality(nauruan,nauru).
nationality(nepalese,nepal).
nationality(nevisian,nevis).
nationality(new_caledonian,new_caledonia).
nationality(new_zealander,new_zealand).
nationality(nicaraguan,nicaragua).
nationality(nigerian,nigeria).
nationality(nigerien,nigeria).
nationality(niuean,niue).
nationality(norfolk_islander,norfolk_islands).
nationality(norwegian,norway).
nationality(omani,oman).
nationality(pakistani,pakistan).
nationality(palauan,palau).
nationality(panamanian,panama).
nationality(papua_new_guinean,papua_new_guinea).
nationality(paraguayan,paraguay).
nationality(peruvian,peru).
nationality(philippine,philippines).
nationality(pitcairn_islander,pitcairn_islands).
nationality(pohnpeian,pohnpei).
nationality(pole,poland).
nationality(polish,poland).
nationality(portuguese,portugal).
nationality(puerto_rican,puerto_rica).
nationality(qatari,qatar).
nationality(reunionese,la_reunion).
nationality(romanian,romania).
nationality(russian,russia).
nationality(rwandan,rwandan).
nationality(sahraoui,sahara).
nationality(sahraouian,sahara).
nationality(sahrawi,sahara).
nationality(sahrawian,sahara).
nationality(saint_lucian,saint_lucia).
nationality(saint_helenian,saint_helena).
nationality(saint_vincentian,saint_vincent).
nationality(salvadoran,salvador).
nationality(sammarinese,san_marino).
nationality(samoan,samoa).
nationality(sao_tomean,sao_tome).
nationality(saudi,saudi_arabia).
nationality(saudi_arabian,saudi_arabia).
nationality(scottish,scotland).
nationality(scot,scotland).
nationality(senegalese,senegal).
nationality(serb,serbia).
nationality(serbian,serbia).
nationality(seychellois,seychelles).
nationality(sierra_leonean,sierra_leona).
nationality(singaporean,singapore).
nationality(slovak,slovakia).
nationality(slovene,slovenia).
nationality(slovenian,slovenia).
nationality(solomon_islander,solomon_islands).
nationality(somali,somalia).
nationality(south_african,south_africa).
nationality(african,africa).
nationality(spaniard,spain).
nationality(spanish,spain).
nationality(sri_lankan,sri_lanka).
nationality(sudanese,sudan).
nationality(surinamer,suriname).
nationality(surinamese,suriname).
nationality(swazi,swaziland).
nationality(swede,sweden).
nationality(swedish,sweden).
nationality(swiss,switzerland).
nationality(syrian,syria).
nationality(taiwanese,taiwan).
nationality(tajikistani,tajikistan).
nationality(tanzanian,tanzania).
nationality(thai,thailand).
nationality(timorese,timor).
nationality(tobagonian,tobago).
nationality(togolese,togo).
nationality(tokelauan,tokelau).
nationality(tongan,tongan).
nationality(trinidadian,trinidad).
nationality(tunisian,tunisia).
nationality(turk,turkey).
nationality(turkish,turkey).
nationality(turkmen,turkey).
nationality(tuvaluan,tuvalu).
nationality(ugandan,uganda).
nationality(ukrainian,ukraine).
nationality(uruguayan,uruguay).
nationality(uzbekistani,uzbekistan).
nationality(venezuelan,venezuela).
nationality(vietnamese,vietnam).
nationality(vincentian,st_vincent).
nationality(virgin_islander,virgin_islands).
nationality(wallisian,wallis).
nationality(yapese,yap).
nationality(yemeni,yemen).
nationality(zambian,zambia).
nationality(zimbabwean,zimbabwe).
