% Built by Ulf Hermjakob, USC/ISI - June 2, 2015
role('have-org-role-9','ARG2','ambassador').
role('have-org-role-9','ARG2','archbishop').
role('have-org-role-9','ARG2','bishop').
role('have-org-role-9','ARG2','CEO').
role('have-org-role-9','ARG2','chairman').
role('have-org-role-9','ARG2','chancellor').
role('have-org-role-9','ARG2','commissioner').
role('have-org-role-9','ARG2','congressman').
role('have-org-role-9','ARG2','congresswoman').
role('have-org-role-9','ARG2','deputy').
role('have-org-role-9','ARG2','dictator').
role('have-org-role-9','ARG2','director').
role('have-org-role-9','ARG2','director-general').
role('have-org-role-9','ARG2','emperor').
role('have-org-role-9','ARG2','empress').
role('have-org-role-9','ARG2','governor').
role('have-org-role-9','ARG2','king').
role('have-org-role-9','ARG2','mayor').
role('have-org-role-9','ARG2','minister').
role('have-org-role-9','ARG2','monarch').
role('have-org-role-9','ARG2','officer').
role('have-org-role-9','ARG2','official').
role('have-org-role-9','ARG2','plenipotentiary').
role('have-org-role-9','ARG2','pope').
role('have-org-role-9','ARG2','premier').
role('have-org-role-9','ARG2','president').
role('have-org-role-9','ARG2','principal').
role('have-org-role-9','ARG2','professor').
role('have-org-role-9','ARG2','queen').
role('have-org-role-9','ARG2','secretary').
role('have-org-role-9','ARG2','secretary-general').
role('have-org-role-9','ARG2','senator').
role('have-org-role-9','ARG2','shah').
role('have-org-role-9','ARG2','spokesman').
role('have-org-role-9','ARG2','spokesperson').
role('have-org-role-9','ARG2','spokeswoman').
role('have-org-role-9','ARG2','treasurer').
role('have-org-role-9','ARG2','undersecretary-general').
role('have-org-role-9','ARG2','activist').
role('have-org-role-9','ARG2','agent').
role('have-org-role-9','ARG2','attorney').
role('have-org-role-9','ARG2','boss').
role('have-org-role-9','ARG2','brigadier-general').
role('have-org-role-9','ARG2','captain').
role('have-org-role-9','ARG2','cardinal').
role('have-org-role-9','ARG2','chief').
role('have-org-role-9','ARG2','citizen').
role('have-org-role-9','ARG2','clerk').
role('have-org-role-9','ARG2','colonel').
role('have-org-role-9','ARG2','colonel-general').
role('have-org-role-9','ARG2','commander').
role('have-org-role-9','ARG2','correspondent').
role('have-org-role-9','ARG2','diplomat').
role('have-org-role-9','ARG2','executive').
role('have-org-role-9','ARG2','general').
role('have-org-role-9','ARG2','lieutenant').
role('have-org-role-9','ARG2','lieutenant-colonel').
role('have-org-role-9','ARG2','lieutenant-general').
role('have-org-role-9','ARG2','major').
role('have-org-role-9','ARG2','matriarch').
role('have-org-role-9','ARG2','militant').
role('have-org-role-9','ARG2','nurse').
role('have-org-role-9','ARG2','patriarch').
role('have-org-role-9','ARG2','personnel').
role('have-org-role-9','ARG2','pilot').
role('have-org-role-9','ARG2','reservist').
role('have-org-role-9','ARG2','seaman').
role('have-org-role-9','ARG2','scientist').
role('have-org-role-9','ARG2','second-in-command').
role('have-org-role-9','ARG2','soldier').
role('have-org-role-9','ARG2','veteran').
role('have-org-role-9','ARG2','wingman').
role('have-org-role-9','ARG2','warrior').
